language: go

services:
  - docker
  
script: 
  - echo "Tesing & Building FlakyHost code"
  - cd flakyhost 
  - go test -v ./...
  - docker image build --tag flakyhost .
  - echo "Tesing & Building AlertLogges code"
  - cd ../alertlogger 
  - go test -v ./...
  - docker image build --tag alertlogger .
