language: go

services:
  - docker

before_install:
  - cd flakyhost && docker image build --tag flakyhost .
  - cd alertlogger && docker image build --tag alertlogger .
script: 
  - cd flakyhost && go test -v ./...
  - cd alertlogger && go test -v ./...
