language: go

services:
  - docker

before_install:
  - cd flakyhost && docker image build --tag flakyhost . && cd ..
  - cd alertlogger && docker image build --tag alertlogger . && cd ..
script: 
  - cd flakyhost && go test -v ./... && cd ..
  - cd alertlogger && go test -v ./... && cd ..
