version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.17.1
    # restart: always
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
      - frontend
    volumes:
      - "./config:/config"
      - "./data/prometheus:/data"
    command: --config.file=/config/prometheus.yml --storage.tsdb.path=/data --storage.tsdb.retention.time=5000h
  blackbox_exporter:
    image: prom/blackbox-exporter:v0.16.0
    ports:
      - "9115:9115"
    # dns: 8.8.8.8
    # restart: always
    ports:
      - "9115:9115"
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml
  alertmanager:
    image: prom/alertmanager:v0.20.0
    # restart: always
    networks:
      - monitoring-network
    ports:
      - "9093:9093"
    volumes:
      - "./data/alertmanager:/data"
      - "./config:/config"
    command: --config.file=/config/alertmanager.yml --storage.path=/data
  alertlogger:
    build: alertlogger
    # restart: always
    networks:
      - monitoring-network
    ports:
      - "9566:8088"
    environment:
      - LOG_ALERT_PATH=/data/alerts.log
    volumes:
      - "./data/alertlogger:/data"
  # Fake endpoints
  flakyhost.com:
    environment:
      - HITS_FAIL_COUNT=10
    build: flakyhost
    # restart: always
    networks:
      - frontend
    ports:
      - "9567:80"
  reliablehost.com:
    environment:
      - HITS_FAIL_COUNT=0
    build: flakyhost
    networks:
      - frontend
    # restart: always
    ports:
      - "9568:80"
networks:
  frontend:
  monitoring-network: